import os
import logging
from typing import List, Dict, Any, Optional
from youtube_shorts.config import ASSETS_BACKGROUNDS_DIR, ASSETS_CLIPS_DIR
from youtube_shorts.ai_video_fetcher import fetch_ai_video_for_scene

logger = logging.getLogger("youtube_shorts.media_fetcher")


class MediaFetcher:
    """
    Direct Prompt-to-Video Engine.
    Takes Markdown/JSON visual prompts generated by Gemini and fetches/generates real 9:16 MP4 motion videos for each scene!
    """

    def __init__(self, clips_dir: str = ASSETS_CLIPS_DIR, backgrounds_dir: str = ASSETS_BACKGROUNDS_DIR):
        self.clips_dir = os.path.abspath(clips_dir)
        self.backgrounds_dir = os.path.abspath(backgrounds_dir)
        os.makedirs(self.clips_dir, exist_ok=True)
        os.makedirs(self.backgrounds_dir, exist_ok=True)

    def fetch_scene_media(self, script_data: Dict[str, Any]) -> List[str]:
        """
        Generates/fetches real 9:16 MP4 videos matching the exact scene prompt (e.g. police officer, hacker)!
        """
        scenes = script_data.get("scenes", [])
        if not scenes:
            return self.get_backup_clips()

        video_paths = []
        for idx, scene in enumerate(scenes):
            v_path = fetch_ai_video_for_scene(scene, idx)
            if v_path and os.path.exists(v_path):
                video_paths.append(v_path)

        return video_paths or self.get_backup_clips()

    def get_backup_clips(self) -> List[str]:
        """Backup MP4 video clips loader."""
        clips = []
        for d in [self.clips_dir, self.backgrounds_dir]:
            if os.path.exists(d):
                for f in os.listdir(d):
                    p = os.path.join(d, f)
                    if f.endswith((".mp4", ".mkv", ".webm")) and os.path.getsize(p) > 50000:
                        clips.append(p)
        return clips


def download_media_clips(queries: List[str], script_data: Optional[Dict[str, Any]] = None, output_dir: Optional[str] = None) -> List[str]:
    fetcher = MediaFetcher()
    if script_data:
        return fetcher.fetch_scene_media(script_data)
    return fetcher.get_backup_clips()
